
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  name: localwindows

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Installing the Node.js into the ubuntu-latest image'

- script: |
    - bash $echo 'hello'
    npm install -g
    npm run test
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '**/TEST-*.xml'
  displayName: 'npm install and build'
